version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0407Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_0407.integrations:Call_refData
  packages:
  - name: SIQA_GIT_0407Project
    version: "1.0"
- serviceName: project.siqa_git_0407.referencedata:refData
  packages:
  - name: SIQA_GIT_0407Project
    version: "1.0"
